app:
  deploymentName: front-end-deployment
  replicaCount: 4
  env: front-end

service:
  enabled: true
  name: frontend-service
  type: ClusterIP
  port: 80

namespace:
  enabled: true
  name: front-qa-namespace

image:
  repository: vaidehisatpute/clonedocker
  pullPolicy: IfNotPresent
  tag: 115
  containerPort: 3000
  containerName: frontendcontainer

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: aks-sc-front-end
  provisioner: file.csi.azure.com

PersistentVolumeClaim:
  enabled: false
  name: aks-pvc

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi








