apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-application
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend-service-k8s
  replicas: 8
  template:
    metadata:
      labels:
        app: backend-service-k8s
    spec:
      securityContext:  #TODO runAsUser, runAsGroup, fsGroup, allowPrivilegeEscalation, and readOnlyRootFilesystem
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        supplementalGroups: [1002]
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: backend-service-k8s
          image: srinu641/spring-application-k8s:v1.02
          ports:
            - containerPort: 1199
          restartPolicy: Always
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-k8s
  namespace: backend
  labels:
    name: backend-service-k8s
spec:
  type:  NotoPort #LoadBalancer
  ports:
    - protocol: http
      port: 80
      targetPort: 1199
  selector:
    app: backend-service-k8s
---