apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deploy
  namespace: backend
  labels:
    app: app-label
    version: v1.0.1
spec:
  selector:
    matchLabels:
      app: app-label
      version: v1.0.1
  replicas: 9
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        version: v1.0.1
    spec:
      containers:
        - name: spring-application-container
          image: srinu641/spring-application-k8s:v1.02
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1199
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "356Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: backend
  labels:
    app: app-label
    version: v1.0.1
spec:
  type: NodePort
  selector:
    app: app-label
    version: v1.0.1
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 1199
---