#TODO ->  Provisioner for Priority Workloads
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: burst-pool
spec:
  template:
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
      kubelet:
        maxPods: 250
  limits:
    cpu: 200
    memory: 2000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 30m
---