kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: nginx-http-scaledobject
  namespace: backend
spec:
  host: myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    deployment: application-deploy
    service: application-service
    port: 80
  replicas:
    min: 0
    max: 20
---