---
# Source: argo-cd-front-end/templates/dev-environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Srinu-rj/helm-kubernetes
    targetRevision: master
    path: helm-charts/front-end
    helm:
      valueFiles:
         -values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa-argo-front-end-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        -CreateNamespace=true
