apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  host: "postgres"
  name: "backendservice"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  postgres_user: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: mysecurepassword
---