apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-disk
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---