apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{- if .Values.namespace.enabled }}
     {{ .Values.namespace.name }}
   {{- else -}}
     {{ .Release.Namespace }}
   {{- end }}
  labels:
    {{- include "app-label" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-label" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "app-label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: {{ .Values.restartPolicy }}
          ports:
            - containerPort: {{ .Values.image_port_number }}
          resources:
            requests:
             {{- toYaml .Values.compute | nindent 12 }}

---