apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "app-label" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app-label" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "app-label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: {{ .Values.restartPolicy }}
          ports:
            - containerPort: {{ .Values.image_port_number }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}

---