apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceApp }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "app-label" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "app-label" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: {{ .Values.service.targetPort }}

---