apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-mem-quota
  namespace: database-production | DevTest | ApiTestTEam
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    requests.cpu: 1 # Todo 400 millicores
    requests.memory: 500Mi # Todo 200 Megabytes
    limits.cpu: 2
    limits.memory: 8Gi
    pods: "10"
    replicationcontrollers: "5"
    secrets: "10"
    configmaps: "10"
    #The total number of PersistentVolumeClaims that can exist in the namespace.
    persistentvolumeclaims: "4"
    services: "5"
    services.nodeports: "2"
---