application:
  name: front-end-qa
  namespace: argocd
  project: default

source:
  repoURL: https://github.com/Srinu-rj/helm-kubernetes
  targetRevision: master
  path: helm-charts/front-end
  helm:
    valueFiles:
      - values-qa.yaml

destination:
  server: https://kubernetes.default.svc
  namespace: qa-namespace

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
