apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress-tls
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    haproxy.org/ssl-redirect: "true"
    #TODO --> whenever user click /api/users that will redirect to /v1/users -> /api(/|$)(.*)
    nginx.ingress.kubernetes.io/rewrite-target: /v1/$2
    # TODO --> HTTP TO HTTPS throw SSL  | RULES-HOST AND TLS-HOST: "*.domain.com"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - hello-world.com
      secretName: ingress-secrets
  rules:
    - host: hello-world.com # TODO WILD CARD DOMAIN -> "*.domain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secured-service
                port:
                  number: 443

---