kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-ingress-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: trouble1
  policyTypes:
    - Ingress
    - Egress
---