apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  namespace:
  annotations:
    kubernetes.io/ingress.bandwidth: "10M"
    kubernetes.io/egress-bandwidth: "30M"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - spring.boot.com
      secretName: testsecret-tls
  rules: # api/address/sva
    - host: spring.boot.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8998
---
