apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: cert-manager
spec:
  secretName: ca-secret
  issuerRef:
    name: ingress-nginx-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - spring.boot.com # must match with in Ingress hostName
