#TODO -> Adjusting an Elasticsearch Cluster
#TODO -> For applications consisting of multiple interdependent components, we might deploy separate PDBs for each component, reflecting their individual availability requirements.
#TODO -> This approach allows us to manage disruptions more granularly, ensuring critical components remain highly available while providing more flexibility for less critical components.
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.12.1
  nodeSets:
    - name: default
      count: 3
  podDisruptionBudget:
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: quickstart
---