application:
  name: backend-qa
  namespace: argocd
  project: default

source:
  repoURL: https://github.com/Srinu-rj/helm-kubernetes
  targetRevision: master
  path: helm-charts/backend
  helm:
    valueFiles:
      - values-qa.yaml

destination:
  server: https://kubernetes.default.svc
  namespace: qa-argo-back-end-namespace

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
