apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "frontend" . | nindent 4 }}
spec:
  selector:
    {{- include "frontend" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
      protocal: http
  type: ClusterIP
